name: Check if PR is up-to-date with develop

on:
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check up-to-date
        run: |
          if git merge-base --is-ancestor origin/master origin/${{ github.head_ref }}; then
            echo "PR is up-to-date with develop branch."
          else
            echo "PR is not up-to-date with develop branch. Please update your branch."
            exit 1
          fi
