name: my first workflow

on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest

    steps:
    - name: Hello world action step
      id : Hello
      uses: 2JS/Actions@master
      with:
        who-to-greet: 'Mona the Octocat'
